on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
name: pipeline despliegue
jobs:
  terraform:
    name: despliegue a al ambiente dev
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      working-directory: ./terraform
      TERRAFORM_TFVARS_BASE64: ${{ secrets.TERRAFORM_TFVARS_BASE64 }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      DOCKERHUB_USUARIO: ${{ secrets.DOCKERHUB_USUARIO }}
      DOCKERHUB_CONTRASENIA: ${{ secrets.DOCKERHUB_CONTRASENIA }}
      DOCKERHUB_REPOSITORIO: ${{ secrets.DOCKERHUB_REPOSITORIO }}
      USUARIO_EC2: ${{ secrets.USUARIO_EC2 }}
      LLAVE_PRIVADA_EC2: ${{ secrets.LLAVE_PRIVADA_EC2 }}
      PUERTO_APLICACION: ${{ secrets.PUERTO_APLICACION }}
    steps:
      - name: bajar codigo al servidor
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        working-directory: ${{ env.working-directory }}
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        working-directory: ${{ env.working-directory }}
        run: terraform init
      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.working-directory }}
        run: terraform validate -no-color

      - name: copiar tfvars al entorno
        working-directory: ${{ env.working-directory }}
        run: echo "${{ env.TERRAFORM_TFVARS_BASE64 }}" | base64 -d > ./terraform.tfvars

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.working-directory }}
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.working-directory }}
        run: terraform apply -auto-approve

      - name: Terraform Output
        id: output
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.6
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: ${{ env.working-directory }}
      - name: 'Use Terraform Output'
        run: echo ${{ steps.output.outputs  }}

      - name: Subida Estado a S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: ${{ env.working-directory }}
          bucket: ${{ env.AWS_S3_BUCKET }}
          bucket-region: ${{ env.AWS_S3_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true

      - name: construir y subir a dockerhub
        uses: docker/build-push-action@v2
        with:
          username: ${{ env.DOCKERHUB_USUARIO }}
          password: ${{ env.DOCKERHUB_CONTRASENIA }}
          repository: ${{ env.DOCKERHUB_REPOSITORIO }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}

      - name: Salida estandar ip instance
        id: endpoint_public
        run: echo "instance_public_ip=$(echo ${{ steps.output.outputs }} | base64 -d |  grep -A2 'value' | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]')" >> $GITHUB_ENV

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          IP_INSTANCE:  ${{ env.instance_public_ip }}
        with:
          host: ${{ env.IP_INSTANCE }}
          username: ${{ env.USUARIO_EC2 }}
          key: ${{ env.LLAVE_PRIVADA_EC2 }}
          script: docker run -p ${{ env.PUERTO_APLICACION }}:${{ env.PUERTO_APLICACION }} --name alcancia-prueba -d ${{ env.DOCKERHUB_REPOSITORIO }}:${{ github.sha }}
