on: push
name: pipeline deploy
jobs:
  pipeline:
    name: despliegue a cluster
    runs-on: ubuntu-20.04
    steps:
      - name: bajar codigo al servidor
        uses: actions/checkout@master
      - name: construir y subir a dockerhub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}