on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
name: pipeline despliegue
jobs:
  terraform:
    name: despliegue a al ambiente dev
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      working-directory: ./terraform
    steps:
      - name: bajar codigo al servidor
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        working-directory: ${{ env.working-directory }}
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        working-directory: ${{ env.working-directory }}
        run: terraform init
      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.working-directory }}
        run: terraform validate -no-color
        
      - name: copiar tfvars al entorno
        working-directory: ${{ env.working-directory }}
        env:
          TERRAFORM_TFVARS_BASE64: ${{ secrets.TERRAFORM_TFVARS_BASE64 }}
        run: echo "${{ secrets.TERRAFORM_TFVARS_BASE64 }}" | base64 -d > ./terraform.tfvars
        
      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.working-directory }}
        env:
          TERRAFORM_TFVARS_BASE64: ${{ secrets.TERRAFORM_TFVARS_BASE64 }}
        run: terraform plan -no-color
      
      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.working-directory }}
        run: terraform apply -auto-approve
      
      - name: Terraform Output
        id: output
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.6
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: ${{ env.working-directory }}
      - name: 'Use Terraform Output'
        run: echo ${{ steps.terraform.outputs  }}
      
      - name: construir y subir a dockerhub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_CONTRASENIA }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORIO }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
          
      - run: echo "${{ steps.apply.outputs }}"
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: $(echo ${{ steps.output.outputs.tf_actions_output }} | jq -r '.elb_dns_name.value.name')
          username: ${{ secrets.USUARIO_EC2 }}
          key: ${{ secrets.LLAVE_PRIVADA_EC2 }}
          script: docker run -p ${{ secrets.PUERTO_APLICACION }}:${{ secrets.PUERTO_APLICACION }} --name alcancia-prueba -d ${{ secrets.DOCKERHUB_REPOSITORIO }}:${{ github.sha }}
